### ISSUE TITLE
Roadmap & Improvements

### ISSUE THREAD

**Issue by dishitpala** [dishitpala/wpvip#1]
## Tasks

- [ ] Update README with proper information
- [ ] Handle errors more efficiently
- [ ] Add rollback feature
- [ ] Add data sync feature https://docs.wpvip.com/vip/export/sql/
- [ ] check if we can use this for memcached for local by flywheel https://gist.github.com/strategio/797087099cea854f1b614a8f81be2935
